{% set python_min = "3.10.0" %}
{% set name = "defectpl" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/defectpl-{{ version }}.tar.gz
  sha256: db84eadc638e599fe8568b4dd1578a52ab1a654b571534f5b1e587f41dde0365

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pyyaml >=6.0.2,<7.0.0
    - numpy >=2.1.2,<3.0.0
    - pymatgen 2024.10.3

test:
  imports:
    - defectpl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Shibu778/defectpl
  summary: A unified package for optical properties of point defects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shibu778
