{% set name = "defectpl" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/defectpl-{{ version }}.tar.gz
  sha256: ab1c92bebbe334e31cc2172cd670bfaabb0e8338ad6951729e6e67f1c603b039

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core >=2.0.0
    - pip
  run:
    - python >=3.10
    - pyyaml >=6.0.2
    - numpy >=2.1.2
    - pymatgen-core >=2026.5.18
    - pymatgen >=2026.5.4
    - click >=8.1.7
    - phonopy >=2.35.0,<3.0.0
    - matplotlib >=3.8.0
    - monty >=2026.5.18

test:
  imports:
    - defectpl
  commands:
    - pip check
  requires:
    - pip
    - python >=3.10

about:
  home: https://github.com/Shibu778/defectpl
  summary: A unified package for optical properties of point defects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shibu778