{% set name = "defectpl" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/defectpl-{{ version }}.tar.gz
  sha256: 4b8357fd54ab9ba5edc27a7a7526a4f3d3737e4f3cc381680fc6f8ef60fc333c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - pyyaml >=6.0.2,<7.0.0
    - numpy >=2.1.2,<3.0.0
    - pymatgen 2024.10.3
    - pathlib >=1.0.1,<2.0.0

test:
  imports:
    - defectpl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Shibu778/defectpl
  summary: A unified package for optical properties of point defects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shibu778
